CREATE OR ALTER PROCEDURE SP_ADMIN_GET_INFO @MACN INT AS
BEGIN

DECLARE @result TABLE (
    tableID INT,
    billID INT,
    date DATE,
    time TIME,
    createdBy NVARCHAR(255),
    isPending BIT,
    isPaid BIT
);

INSERT INTO @result (tableID, billID, date, time, createdBy, isPending, isPaid)
SELECT 
    BAN.MABAN AS TABLEID,
    BAN.MAHD AS BILLID,
    CASE WHEN BAN.MAHD IS NOT NULL THEN 
        (SELECT TOP 1 HOADON.NgayLap 
         FROM HOADON 
         WHERE MAHD = BAN.MAHD 
         ORDER BY NgayLap DESC) 
    ELSE NULL END AS DATE,

    CASE WHEN BAN.MAHD IS NOT NULL THEN 
        (SELECT TOP 1 CONVERT(DATETIME, HOADON.NgayLap) 
         FROM HOADON 
         WHERE MAHD = BAN.MAHD 
         ORDER BY NgayLap DESC) 
    ELSE NULL END AS TIME,

    CASE WHEN BAN.MAHD IS NOT NULL THEN 
        (SELECT TOP 1 NHANVIEN.HOTEN 
         FROM NHANVIEN 
         WHERE NHANVIEN.MaNV = 
             (SELECT TOP 1 PHIEUDATMON.MaNV 
              FROM PHIEUDATMON 
              WHERE PHIEUDATMON.MaHD = BAN.MAHD 
              ORDER BY PHIEUDATMON.NgayLap DESC)) 
    ELSE NULL END AS CREATEDBY,

	-- NEU BAN CO CHUA MA HOA DON THI BAN DANG PHUC VU
    CASE WHEN BAN.MaHD IS NOT NULL THEN 1 ELSE 0 END AS ISPENDING,

	-- NEU BAN CO CHUA MAHD VA MAHD NAY DUOC TIM THAY TRONG DANH SACH DATBAN THI HOA DON DO DA THANH TOAN!
    CASE WHEN BAN.MAHD IS NOT NULL AND BAN.MAHD IN 
        (SELECT MAHD 
         FROM DATBAN 
         WHERE MaCN = @MACN) 
    THEN 1 ELSE 0 END AS ISPAID

FROM BAN
WHERE BAN.MaCN = @MACN;

SELECT * FROM @result;

END;
GO

CREATE OR ALTER PROCEDURE SP_QUERY_PAGE
    @QUERY VARCHAR(MAX),
	@PAGE INT = 1,  
    @PAGESIZE INT = 25
AS
BEGIN

    DECLARE @sql NVARCHAR(MAX);
    SET @sql = @QUERY + ' ORDER BY (SELECT NULL) OFFSET ' + 
    CAST(@PAGESIZE * (@page - 1) AS VARCHAR) + 
    ' ROWS FETCH NEXT ' + CAST(@PAGESIZE AS VARCHAR) + 
    ' ROWS ONLY';
    EXEC sp_executesql @sql;
END;
GO

--drop procedure SP_getdishes

CREATE OR ALTER PROCEDURE SP_GETDISHES @MACN INT, @PAGESIZE INT, @PAGE INT, @CATEGORY NVARCHAR(100) = '%'
AS
BEGIN
SELECT PHUCVU.isServed, MONAN.* FROM PHUCVU JOIN MONAN ON MONAN.MaMon = PHUCVU.MaMon
WHERE MACN = @MACN AND MONAN.PhanLoai LIKE @CATEGORY ORDER BY MONAN.MaMon ASC
OFFSET @PAGESIZE *(@PAGE - 1) ROWS FETCH NEXT @PAGESIZE ROWS ONLY;
END;
go

SELECT MONAN.* FROM THUCDON JOIN MONAN 
                ON THUCDON.MaMon = MONAN.MaMon 
                WHERE THUCDON.MaKV = 'MN' AND PHANLOAI LIKE '%'




