USE QLY_NHAHANG
GO

-- Bước 1: Tạo Filegroup cho các phân vùng
--Tạo Filegroup cho từng tháng, năm
ALTER DATABASE QLY_NHAHANG
ADD FILEGROUP FG_HOADON_01_2024
GO

ALTER DATABASE QLY_NHAHANG
ADD FILEGROUP FG_HOADON_02_2024
GO

ALTER DATABASE QLY_NHAHANG
ADD FILEGROUP FG_HOADON_03_2024
GO

ALTER DATABASE QLY_NHAHANG
ADD FILEGROUP FG_HOADON_04_2024
GO

ALTER DATABASE QLY_NHAHANG
ADD FILEGROUP FG_HOADON_05_2024
GO

ALTER DATABASE QLY_NHAHANG
ADD FILEGROUP FG_HOADON_06_2024
GO

ALTER DATABASE QLY_NHAHANG
ADD FILEGROUP FG_HOADON_07_2024
GO

ALTER DATABASE QLY_NHAHANG
ADD FILEGROUP FG_HOADON_08_2024
GO

ALTER DATABASE QLY_NHAHANG
ADD FILEGROUP FG_HOADON_09_2024
GO

ALTER DATABASE QLY_NHAHANG
ADD FILEGROUP FG_HOADON_10_2024
GO

ALTER DATABASE QLY_NHAHANG
ADD FILEGROUP FG_HOADON_11_2024
GO

ALTER DATABASE QLY_NHAHANG
ADD FILEGROUP FG_HOADON_12_2024
GO

-- Tạo FILE cho filegroup
ALTER DATABASE QLY_NHAHANG
ADD FILE
(
    NAME = 'HOADON_01_2024_FILE',
    FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\HOADON_01_2024_FILE.ndf',
    SIZE = 1MB,
    MAXSIZE = UNLIMITED,
    FILEGROWTH = 10MB
) TO FILEGROUP FG_HOADON_01_2024;
GO

ALTER DATABASE QLY_NHAHANG
ADD FILE
(
    NAME = 'HOADON_02_2024_FILE',
    FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\HOADON_02_2024_FILE.ndf',
    SIZE = 1MB,
    MAXSIZE = UNLIMITED,
    FILEGROWTH = 10MB
) TO FILEGROUP FG_HOADON_02_2024;
GO

ALTER DATABASE QLY_NHAHANG
ADD FILE
(
    NAME = 'HOADON_03_2024_FILE',
    FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\HOADON_03_2024_FILE.ndf',
    SIZE = 1MB,
    MAXSIZE = UNLIMITED,
    FILEGROWTH = 10MB
) TO FILEGROUP FG_HOADON_03_2024;
GO

ALTER DATABASE QLY_NHAHANG
ADD FILE
(
    NAME = 'HOADON_04_2024_FILE',
    FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\HOADON_04_2024_FILE.ndf',
    SIZE = 1MB,
    MAXSIZE = UNLIMITED,
    FILEGROWTH = 10MB
) TO FILEGROUP FG_HOADON_04_2024;
GO

ALTER DATABASE QLY_NHAHANG
ADD FILE
(
    NAME = 'HOADON_05_2024_FILE',
    FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\HOADON_05_2024_FILE.ndf',
    SIZE = 1MB,
    MAXSIZE = UNLIMITED,
    FILEGROWTH = 10MB
) TO FILEGROUP FG_HOADON_05_2024;
GO

ALTER DATABASE QLY_NHAHANG
ADD FILE
(
    NAME = 'HOADON_06_2024_FILE',
    FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\HOADON_06_2024_FILE.ndf',
    SIZE = 1MB,
    MAXSIZE = UNLIMITED,
    FILEGROWTH = 10MB
) TO FILEGROUP FG_HOADON_06_2024;
GO

ALTER DATABASE QLY_NHAHANG
ADD FILE
(
    NAME = 'HOADON_07_2024_FILE',
    FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\HOADON_07_2024_FILE.ndf',
    SIZE = 1MB,
    MAXSIZE = UNLIMITED,
    FILEGROWTH = 10MB
) TO FILEGROUP FG_HOADON_07_2024;
GO

ALTER DATABASE QLY_NHAHANG
ADD FILE
(
    NAME = 'HOADON_08_2024_FILE',
    FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\HOADON_08_2024_FILE.ndf',
    SIZE = 1MB,
    MAXSIZE = UNLIMITED,
    FILEGROWTH = 10MB
) TO FILEGROUP FG_HOADON_08_2024;
GO

ALTER DATABASE QLY_NHAHANG
ADD FILE
(
    NAME = 'HOADON_09_2024_FILE',
    FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\HOADON_09_2024_FILE.ndf',
    SIZE = 1MB,
    MAXSIZE = UNLIMITED,
    FILEGROWTH = 10MB
) TO FILEGROUP FG_HOADON_09_2024;
GO

ALTER DATABASE QLY_NHAHANG
ADD FILE
(
    NAME = 'HOADON_10_2024_FILE',
    FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\HOADON_10_2024_FILE.ndf',
    SIZE = 1MB,
    MAXSIZE = UNLIMITED,
    FILEGROWTH = 10MB
) TO FILEGROUP FG_HOADON_10_2024;
GO

ALTER DATABASE QLY_NHAHANG
ADD FILE
(
    NAME = 'HOADON_11_2024_FILE',
    FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\HOADON_11_2024_FILE.ndf',
    SIZE = 1MB,
    MAXSIZE = UNLIMITED,
    FILEGROWTH = 10MB
) TO FILEGROUP FG_HOADON_11_2024;
GO

ALTER DATABASE QLY_NHAHANG
ADD FILE
(
    NAME = 'HOADON_12_2024_FILE',
    FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\HOADON_12_2024_FILE.ndf',
    SIZE = 1MB,
    MAXSIZE = UNLIMITED,
    FILEGROWTH = 10MB
) TO FILEGROUP FG_HOADON_12_2024;
GO

-- Bước 2: Tạo Partition Function
-- Partition cho bảng HOADON (phân theo tháng)
CREATE PARTITION FUNCTION PF_HOADON (DATE)
AS RANGE RIGHT FOR VALUES 
(
    '2024-01-01', '2024-02-01', '2024-03-01', '2024-04-01', '2024-05-01', 
    '2024-06-01', '2024-07-01', '2024-08-01', '2024-09-01', '2024-10-01', 
    '2024-11-01', '2024-12-01'
);
GO

-- Bước 3: Tạo Partition Scheme
CREATE PARTITION SCHEME PS_HOADON
AS PARTITION PF_HOADON TO 
    (FG_HOADON_01_2024, FG_HOADON_02_2024, FG_HOADON_03_2024, FG_HOADON_04_2024, 
     FG_HOADON_05_2024, FG_HOADON_06_2024, FG_HOADON_07_2024, FG_HOADON_08_2024, 
     FG_HOADON_09_2024, FG_HOADON_10_2024, FG_HOADON_11_2024, FG_HOADON_12_2024,
	 [PRIMARY]);
GO

-- Bước 4: Tạo Clustered Index cho HOADON
-- Xóa Primary Key cũ và các constraint
ALTER TABLE PHIEUDATMON
DROP CONSTRAINT FK_PHIEUDATMON_HOADON

ALTER TABLE PHIEUDANHGIA
DROP CONSTRAINT FK_PHIEUDANHGIA_HOADON

ALTER TABLE BAN
DROP CONSTRAINT FK_BAN_HOADON;

ALTER TABLE HOADON
DROP CONSTRAINT PK_HOADON;

-- Tạo primary key với non clustered và tạo lại các constraint đã xóa
ALTER TABLE HOADON
ADD PRIMARY KEY 
NONCLUSTERED (MaHD)
ON [PRIMARY];

ALTER TABLE PHIEUDATMON
ADD CONSTRAINT FK_PHIEUDATMON_HOADON
FOREIGN KEY (MaHD) REFERENCES HOADON(MaHD);

ALTER TABLE PHIEUDANHGIA
ADD CONSTRAINT FK_PHIEUDANHGIA_HOADON
FOREIGN KEY (MaHD) REFERENCES HOADON(MaHD);

ALTER TABLE BAN
ADD CONSTRAINT FK_BAN_HOADON
FOREIGN KEY (MaHD) REFERENCES HOADON(MaHD)

CREATE CLUSTERED INDEX IX_HOADON_DATE
ON HOADON
(
	NGAYLAP
) ON PS_HOADON(NGAYLAP)