USE QLY_NHAHANG
GO

-- Bước 1: Tạo Filegroup cho các phân vùng
--Tạo Filegroup cho từng năm
ALTER DATABASE QLY_NHAHANG
ADD FILEGROUP FG_HOADON_2010
GO

ALTER DATABASE QLY_NHAHANG
ADD FILEGROUP FG_HOADON_2011
GO

ALTER DATABASE QLY_NHAHANG
ADD FILEGROUP FG_HOADON_2012
GO

ALTER DATABASE QLY_NHAHANG
ADD FILEGROUP FG_HOADON_2013
GO

ALTER DATABASE QLY_NHAHANG
ADD FILEGROUP FG_HOADON_2014
GO

ALTER DATABASE QLY_NHAHANG
ADD FILEGROUP FG_HOADON_2015
GO

ALTER DATABASE QLY_NHAHANG
ADD FILEGROUP FG_HOADON_2016
GO

ALTER DATABASE QLY_NHAHANG
ADD FILEGROUP FG_HOADON_2017
GO

ALTER DATABASE QLY_NHAHANG
ADD FILEGROUP FG_HOADON_2018
GO

ALTER DATABASE QLY_NHAHANG
ADD FILEGROUP FG_HOADON_2019
GO

ALTER DATABASE QLY_NHAHANG
ADD FILEGROUP FG_HOADON_2020
GO

ALTER DATABASE QLY_NHAHANG
ADD FILEGROUP FG_HOADON_2021
GO

ALTER DATABASE QLY_NHAHANG
ADD FILEGROUP FG_HOADON_2022
GO

ALTER DATABASE QLY_NHAHANG
ADD FILEGROUP FG_HOADON_2023
GO

ALTER DATABASE QLY_NHAHANG
ADD FILEGROUP FG_HOADON_2024
GO

ALTER DATABASE QLY_NHAHANG
ADD FILEGROUP FG_HOADON_2025
GO

-- Tạo FILE cho filegroup
ALTER DATABASE QLY_NHAHANG
ADD FILE
(
    NAME = 'HOADON_2010_FILE',
    FILENAME = '/var/opt/mssql/data/HOADON_2010_FILE.ndf',
    SIZE = 1MB,
    MAXSIZE = UNLIMITED,
    FILEGROWTH = 10MB
) TO FILEGROUP FG_HOADON_2010;
GO

ALTER DATABASE QLY_NHAHANG
ADD FILE
(
    NAME = 'HOADON_2011_FILE',
    FILENAME = '/var/opt/mssql/data/HOADON_2011_FILE.ndf',
    SIZE = 1MB,
    MAXSIZE = UNLIMITED,
    FILEGROWTH = 10MB
) TO FILEGROUP FG_HOADON_2011;
GO

ALTER DATABASE QLY_NHAHANG
ADD FILE
(
    NAME = 'HOADON_2012_FILE',
    FILENAME = '/var/opt/mssql/data/HOADON_2012_FILE.ndf',
    SIZE = 1MB,
    MAXSIZE = UNLIMITED,
    FILEGROWTH = 10MB
) TO FILEGROUP FG_HOADON_2012;
GO

ALTER DATABASE QLY_NHAHANG
ADD FILE
(
    NAME = 'HOADON_2013_FILE',
    FILENAME = '/var/opt/mssql/data/HOADON_2013_FILE.ndf',
    SIZE = 1MB,
    MAXSIZE = UNLIMITED,
    FILEGROWTH = 10MB
) TO FILEGROUP FG_HOADON_2013;
GO

ALTER DATABASE QLY_NHAHANG
ADD FILE
(
    NAME = 'HOADON_2014_FILE',
    FILENAME = '/var/opt/mssql/data/HOADON_2014_FILE.ndf',
    SIZE = 1MB,
    MAXSIZE = UNLIMITED,
    FILEGROWTH = 10MB
) TO FILEGROUP FG_HOADON_2014;
GO

ALTER DATABASE QLY_NHAHANG
ADD FILE
(
    NAME = 'HOADON_2015_FILE',
    FILENAME = '/var/opt/mssql/data/HOADON_2015_FILE.ndf',
    SIZE = 1MB,
    MAXSIZE = UNLIMITED,
    FILEGROWTH = 10MB
) TO FILEGROUP FG_HOADON_2015;
GO

ALTER DATABASE QLY_NHAHANG
ADD FILE
(
    NAME = 'HOADON_2016_FILE',
    FILENAME = '/var/opt/mssql/data/HOADON_2016_FILE.ndf',
    SIZE = 1MB,
    MAXSIZE = UNLIMITED,
    FILEGROWTH = 10MB
) TO FILEGROUP FG_HOADON_2016;
GO

ALTER DATABASE QLY_NHAHANG
ADD FILE
(
    NAME = 'HOADON_2017_FILE',
    FILENAME = '/var/opt/mssql/data/HOADON_2017_FILE.ndf',
    SIZE = 1MB,
    MAXSIZE = UNLIMITED,
    FILEGROWTH = 10MB
) TO FILEGROUP FG_HOADON_2017;
GO

ALTER DATABASE QLY_NHAHANG
ADD FILE
(
    NAME = 'HOADON_2018_FILE',
    FILENAME = '/var/opt/mssql/data/HOADON_2018_FILE.ndf',
    SIZE = 1MB,
    MAXSIZE = UNLIMITED,
    FILEGROWTH = 10MB
) TO FILEGROUP FG_HOADON_2018;
GO

ALTER DATABASE QLY_NHAHANG
ADD FILE
(
    NAME = 'HOADON_2019_FILE',
    FILENAME = '/var/opt/mssql/data/HOADON_2019_FILE.ndf',
    SIZE = 1MB,
    MAXSIZE = UNLIMITED,
    FILEGROWTH = 10MB
) TO FILEGROUP FG_HOADON_2019;
GO

ALTER DATABASE QLY_NHAHANG
ADD FILE
(
    NAME = 'HOADON_2020_FILE',
    FILENAME = '/var/opt/mssql/data/HOADON_2020_FILE.ndf',
    SIZE = 1MB,
    MAXSIZE = UNLIMITED,
    FILEGROWTH = 10MB
) TO FILEGROUP FG_HOADON_2020;
GO

ALTER DATABASE QLY_NHAHANG
ADD FILE
(
    NAME = 'HOADON_2021_FILE',
    FILENAME = '/var/opt/mssql/data/HOADON_2021_FILE.ndf',
    SIZE = 1MB,
    MAXSIZE = UNLIMITED,
    FILEGROWTH = 10MB
) TO FILEGROUP FG_HOADON_2021;
GO

ALTER DATABASE QLY_NHAHANG
ADD FILE
(
    NAME = 'HOADON_2022_FILE',
    FILENAME = '/var/opt/mssql/data/HOADON_2022_FILE.ndf',
    SIZE = 1MB,
    MAXSIZE = UNLIMITED,
    FILEGROWTH = 10MB
) TO FILEGROUP FG_HOADON_2022;
GO

ALTER DATABASE QLY_NHAHANG
ADD FILE
(
    NAME = 'HOADON_2023_FILE',
    FILENAME = '/var/opt/mssql/data/HOADON_2023_FILE.ndf',
    SIZE = 1MB,
    MAXSIZE = UNLIMITED,
    FILEGROWTH = 10MB
) TO FILEGROUP FG_HOADON_2023;
GO

ALTER DATABASE QLY_NHAHANG
ADD FILE
(
    NAME = 'HOADON_2024_FILE',
    FILENAME = '/var/opt/mssql/data/HOADON_2024_FILE.ndf',
    SIZE = 1MB,
    MAXSIZE = UNLIMITED,
    FILEGROWTH = 10MB
) TO FILEGROUP FG_HOADON_2024;
GO

ALTER DATABASE QLY_NHAHANG
ADD FILE
(
    NAME = 'HOADON_2025_FILE',
    FILENAME = '/var/opt/mssql/data/HOADON_2025_FILE.ndf',
    SIZE = 1MB,
    MAXSIZE = UNLIMITED,
    FILEGROWTH = 10MB
) TO FILEGROUP FG_HOADON_2025;
GO

-- Bước 2: Tạo Partition Function
-- Partition cho bảng HOADON (theo năm)
CREATE PARTITION FUNCTION PF_HOADON (DATE)
AS RANGE RIGHT FOR VALUES 
(
    '2010-01-01', '2011-01-01', '2012-01-01', '2013-01-01', 
	'2014-01-01', '2015-01-01',	'2016-01-01', '2017-01-01', 
	'2018-01-01', '2019-01-01', '2020-01-01', '2021-01-01', 
	'2022-01-01', '2023-01-01', '2024-01-01', '2025-01-01'
);
GO

-- Bước 3: Tạo Partition Scheme
CREATE PARTITION SCHEME PS_HOADON
AS PARTITION PF_HOADON TO 
    (
        [PRIMARY], FG_HOADON_2010, FG_HOADON_2011, FG_HOADON_2012, FG_HOADON_2013, 
		FG_HOADON_2014, FG_HOADON_2015, FG_HOADON_2016, FG_HOADON_2017, 
		FG_HOADON_2018, FG_HOADON_2019, FG_HOADON_2020, FG_HOADON_2021, 
		FG_HOADON_2022, FG_HOADON_2023, FG_HOADON_2024, FG_HOADON_2025
    );
GO

-- Bước 4: Tạo Clustered Index cho HOADON
-- Xóa Primary Key cũ và các constraint
ALTER TABLE PHIEUDATMON
DROP CONSTRAINT FK_PHIEUDATMON_HOADON;
GO

ALTER TABLE PHIEUDANHGIA
DROP CONSTRAINT FK_PHIEUDANHGIA_HOADON;
GO

ALTER TABLE BAN
DROP CONSTRAINT FK_BAN_HOADON;
GO

ALTER TABLE DATBAN
DROP CONSTRAINT FK_DATBAN_HOADON;
GO

ALTER TABLE HOADON
DROP CONSTRAINT PK_HOADON;
GO

-- Tạo primary key với non clustered và tạo lại các constraint đã xóa
ALTER TABLE HOADON
ADD PRIMARY KEY 
NONCLUSTERED (MaHD)
ON [PRIMARY];
GO

ALTER TABLE PHIEUDATMON
ADD CONSTRAINT FK_PHIEUDATMON_HOADON
FOREIGN KEY (MaHD) REFERENCES HOADON(MaHD);
GO

ALTER TABLE PHIEUDANHGIA
ADD CONSTRAINT FK_PHIEUDANHGIA_HOADON
FOREIGN KEY (MaHD) REFERENCES HOADON(MaHD);
GO

ALTER TABLE BAN
ADD CONSTRAINT FK_BAN_HOADON
FOREIGN KEY (MaHD) REFERENCES HOADON(MaHD);
GO

ALTER TABLE DATBAN
ADD CONSTRAINT FK_DATBAN_HOADON
FOREIGN KEY (MaHD) REFERENCES HOADON(MaHD);
GO

CREATE CLUSTERED INDEX IX_HOADON_DATE
ON HOADON
(
	NGAYLAP
) ON PS_HOADON(NGAYLAP);
GO

/* Kiểm thử
--Xem filegroup đã tạo
SELECT name as [File Group Name]
FROM sys.filegroups
WHERE type = 'FG'
GO 

-- Confirm Datafiles
SELECT name as [DB FileName],physical_name as         
[DB File Path]
FROM sys.database_files
where type_desc = 'ROWS'
GO


SELECT distinct p.partition_number AS PartitionNumber,
    f.name AS PartitionFilegroup,
    p.rows AS NumberOfRows
FROM sys.partitions p JOIN sys.destination_data_spaces dds
    ON p.partition_number = dds.destination_id
JOIN sys.filegroups f ON dds.data_space_id = f.data_space_id
WHERE OBJECT_NAME(OBJECT_ID) = 'HOADON';
GO

SELECT Year(NgayLap), count(*)
FROM HOADON
GROUP BY YEAR(NgayLap)
ORDER By Year(NgayLap);
GO

SELECT * 
FROM sys.partition_functions 
WHERE name = 'PF_HOADON';
GO

SELECT * 
FROM sys.partition_schemes 
WHERE name = 'PS_HOADON';
GO

SELECT p.partition_number, COUNT(*)
FROM sys.partitions p
JOIN sys.destination_data_spaces dds ON p.partition_number = dds.destination_id
JOIN sys.filegroups f ON dds.data_space_id = f.data_space_id
WHERE f.name = 'FG_HOADON_2010'
GROUP BY p.partition_number;

SELECT p.partition_number AS PartitionNumber,
       f.name AS PartitionFilegroup,
       p.rows AS NumberOfRows
FROM sys.partitions p
JOIN sys.destination_data_spaces dds
    ON p.partition_number = dds.destination_id
JOIN sys.filegroups f
    ON dds.data_space_id = f.data_space_id
WHERE OBJECT_NAME(p.object_id) = 'HOADON';
*/