USE QLY_NHAHANG
GO

CREATE PROCEDURE SP_PHIEUDATMON_INSERT
    @MaPhieu INT,
    @NgayLap DATE NOT NULL,
    @MaBan NVARCHAR(50) NOT NULL,
    @TongTien DECIMAL(18, 2),
    @MAKH INT,
    @MaNV INT NOT NULL,
    @MaHD INT
AS
BEGIN
    INSERT INTO PHIEUDATMON
    VALUES (@MaPhieu, @NgayLap, @MaBan, @TongTien, @MAKH, @MaNV, @MaHD)
END;
GO

CREATE PROCEDURE SP_PHIEUDATMON_UPDATE
    @MaPhieu INT,
    @NgayLap DATE NOT NULL,
    @MaBan NVARCHAR(50) NOT NULL,
    @TongTien DECIMAL(18, 2),
    @MAKH INT,
    @MaNV INT NOT NULL,
    @MaHD INT
AS 
BEGIN
    UPDATE PHIEUDATMON
    SET NgayLap = @NgayLap, MaBan = @MaBan, TongTien = @TongTien, MaKH = @MAKH, MaNV = @MaNV, MaHD = @MaHD
    WHERE MaPhieu = @MaPhieu;
END;
GO

CREATE PROCEDURE SP_PHIEUDATMON_DELETE
    @MaPhieu INT
AS
BEGIN
    DELETE FROM PHIEUDATMON
    WHERE MaPhieu = @MaPhieu;
END;
GO

CREATE PROCEDURE SP_PHIEUDATMON_GETALL
AS
BEGIN
    SELECT * FROM PHIEUDATMON;
END;