USE QLY_NHAHANG;
GO

-- *** Bảng KHACHHANG ***
-- Truy vấn tìm kiếm khách hàng theo SDT với index và không có index
CREATE NONCLUSTERED INDEX IDX_KHACHHANG_SDT ON KHACHHANG(SDT);
SELECT * FROM KHACHHANG WHERE SDT = '08073405359';
DROP INDEX IDX_KHACHHANG_SDT ON KHACHHANG;
GO

SELECT * FROM KHACHHANG WHERE SDT = '08073405359';
GO

-- Truy vấn tìm kiếm khách hàng theo Email với index và không có index
CREATE NONCLUSTERED INDEX IDX_KHACHHANG_Email ON KHACHHANG(Email);
SELECT * FROM KHACHHANG WHERE Email = 'user246000@example.realtor';
DROP INDEX IDX_KHACHHANG_Email ON KHACHHANG;
GO

SELECT * FROM KHACHHANG WHERE Email = 'user246000@example.realtor';
GO

-- *** Bảng THETHANHVIEN ***
-- Truy vấn tìm kiếm thẻ thành viên theo MaKH với index và không có index
CREATE NONCLUSTERED INDEX IDX_THETHANHVIEN_MaKH ON THETHANHVIEN(MaKH);
SELECT * FROM THETHANHVIEN WHERE MaKH = 258001;
DROP INDEX IDX_THETHANHVIEN_MaKH ON THETHANHVIEN;
GO

SELECT * FROM THETHANHVIEN WHERE MaKH = 258001;
GO

-- Truy vấn tìm kiếm thẻ thành viên theo NgayLap với index và không có index
CREATE NONCLUSTERED INDEX IDX_THETHANHVIEN_NgayLap ON THETHANHVIEN(NgayLap);
SELECT * FROM THETHANHVIEN WHERE NgayLap = '20210419';
DROP INDEX IDX_THETHANHVIEN_NgayLap ON THETHANHVIEN;
GO

SELECT * FROM THETHANHVIEN WHERE NgayLap = '20210419';
GO

-- *** Bảng MONAN ***
-- Truy vấn tìm kiếm món ăn theo TenMon với index và không có index
CREATE NONCLUSTERED INDEX IDX_MONAN_TenMon ON MONAN(TenMon);
SELECT * FROM MONAN WHERE TenMon = 'SUSHI WORLD MAKI';
DROP INDEX IDX_MONAN_TenMon ON MONAN;
GO

SELECT * FROM MONAN WHERE TenMon = 'SUSHI WORLD MAKI';
GO

-- *** Bảng HOADON *** CHƯA CÓ BẢNG DỮ LIỆU
-- Truy vấn tìm kiếm hóa đơn theo MaThe với index và không có index
CREATE NONCLUSTERED INDEX IDX_HOADON_MaThe ON HOADON(MaThe);
SELECT * FROM HOADON WHERE MaThe = 'T12345';
DROP INDEX IDX_HOADON_MaThe ON HOADON;
GO

SELECT * FROM HOADON WHERE MaThe = 'T12345';
GO

-- Truy vấn tìm kiếm hóa đơn theo NgayLap với index và không có index
CREATE NONCLUSTERED INDEX IDX_HOADON_NgayLap ON HOADON(NgayLap);
SELECT * FROM HOADON WHERE NgayLap = '2024-11-18';
DROP INDEX IDX_HOADON_NgayLap ON HOADON;
GO

SELECT * FROM HOADON WHERE NgayLap = '2024-11-18';
GO

-- *** Bảng PHIEUDATMON ***
-- Truy vấn tìm kiếm phiếu đặt món theo MaKH với index và không có index
CREATE NONCLUSTERED INDEX IDX_PHIEUDATMON_MaKH ON PHIEUDATMON(MaKH);
SELECT * FROM PHIEUDATMON WHERE MaKH = 258001;
DROP INDEX IDX_PHIEUDATMON_MaKH ON PHIEUDATMON;
GO

SELECT * FROM PHIEUDATMON WHERE MaKH = 258001;
GO

-- Truy vấn tìm kiếm phiếu đặt món theo MaNV với index và không có index
CREATE NONCLUSTERED INDEX IDX_PHIEUDATMON_MaNV ON PHIEUDATMON(MaNV);
SELECT * FROM PHIEUDATMON WHERE MaNV = 4604;
DROP INDEX IDX_PHIEUDATMON_MaNV ON PHIEUDATMON;
GO

SELECT * FROM PHIEUDATMON WHERE MaNV = 4604;
GO

--CHƯA CÓ BẢNG DỮ LIỆU
-- Truy vấn tìm kiếm phiếu đặt món theo MaBan với index và không có index
CREATE NONCLUSTERED INDEX IDX_PHIEUDATMON_MaBan ON PHIEUDATMON(MaBan);
SELECT * FROM PHIEUDATMON WHERE MaBan = 789;
DROP INDEX IDX_PHIEUDATMON_MaBan ON PHIEUDATMON;
GO

SELECT * FROM PHIEUDATMON WHERE MaBan = 789;
GO

-- *** Bảng CHONMON *** CHƯA CÓ BẢNG DỮ LIỆU
-- Truy vấn tìm kiếm phiếu chọn món theo MaPhieu và MaMon với index và không có index
CREATE NONCLUSTERED INDEX IDX_CHONMON_MaPhieu_MaMon ON CHONMON(MaPhieu, MaMon);
SELECT * FROM CHONMON WHERE MaPhieu = 789 AND MaMon = 101;
DROP INDEX IDX_CHONMON_MaPhieu_MaMon ON CHONMON;
GO

SELECT * FROM CHONMON WHERE MaPhieu = 789 AND MaMon = 101;
GO

-- *** Bảng DATBAN *** CHƯA CÓ BẢNG DỮ LIỆU
-- Truy vấn tìm kiếm thông tin đặt bàn theo NgayDat với index và không có index
CREATE NONCLUSTERED INDEX IDX_DATBAN_NgayDat ON DATBAN(NgayDat);
SELECT * FROM DATBAN WHERE NgayDat = '2024-11-18';
DROP INDEX IDX_DATBAN_NgayDat ON DATBAN;
GO

SELECT * FROM DATBAN WHERE NgayDat = '2024-11-18';
GO