use QLY_NHAHANG
GO

-- Tạo Index cho các bảng dữ liệu
-- Bảng THETHANHVIEN
CREATE NONCLUSTERED INDEX IDX_THETHANHVIEN_NgayLap ON THETHANHVIEN(NgayLap) --6

-- Bảng HOADON
CREATE NONCLUSTERED INDEX IDX_HOADON_MaCN ON HOADON(MaCN); --5

-- Bảng PHIEUDANHGIA
CREATE NONCLUSTERED INDEX IDX_PHIEUDANHGIA_MaHD ON PHIEUDANHGIA(MaHD); --4

-- Bảng PHIEUDATMON
CREATE NONCLUSTERED INDEX IDX_PHIEUDATMON_MaNV ON PHIEUDATMON(MaNV); --3
CREATE NONCLUSTERED INDEX IDX_PHIEUDATMON_MaHD ON PHIEUDATMON(MaHD); --2
CREATE NONCLUSTERED INDEX IDX_PHIEUDATMON_MaBan ON PHIEUDATMON(MaBan); --6????

-- Bảng DATBAN
CREATE NONCLUSTERED INDEX IDX_DATBAN_HOADON ON DATBAN(MaHD); --1