 USE QLY_NHAHANG;
 GO

CREATE NONCLUSTERED INDEX IDX_BAN_MaHD ON BAN (MaHD);
CREATE NONCLUSTERED INDEX IDX_PHIEUDANHGIA_MaHD ON PHIEUDANHGIA (MaHD);
CREATE NONCLUSTERED INDEX IDX_PHIEUDATMON_MaHD ON PHIEUDATMON (MaHD);
CREATE NONCLUSTERED INDEX IDX_HOADON_MaCN ON HOADON (NgayLap, MaCN) INCLUDE (TongHoaDon);
CREATE NONCLUSTERED INDEX IDX_THETHANHVIEN_LoaiThe_DiemTichLuy_NgayDatThe ON THETHANHVIEN (LoaiThe, DiemTichLuy, NgayDatThe);
CREATE NONCLUSTERED INDEX IDX_THETHANHVIEN_NgayLap ON THETHANHVIEN (NgayLap) INCLUDE (MaKH, MaNV);
CREATE NONCLUSTERED INDEX IDX_PHIEUDATMON_MaNV ON PHIEUDATMON (MaNV);

-- Tính tổng hóa đơn từ các phiếu đặt món trong sp_Checkout (IDX_PHIEUDATMON_MaHD)
DECLARE @MaHD INT = 112;
UPDATE HOADON
SET TongHoaDon = (SELECT SUM(TongTien)
					FROM PhieuDatMon pd
					WHERE pd.MaHD = @MaHD)
WHERE MaHD = @MaHD;

-- Tính điểm phục vụ nhân viên từ fn_DiemPhucVuNhanVien (IDX_PHIEUDANHGIA_MaHD, IDX_PHIEUDATMON_MaHD, IDX_PHIEUDATMON_MaNV)
DECLARE @MaNV INT = 1300;
SELECT AVG(DiemPhucVu)
FROM PHIEUDANHGIA PDG
JOIN HOADON HD ON PDG.MaHD = HD.MaHD
JOIN PHIEUDATMON PDM ON HD.MaHD = PDM.MaHD
WHERE PDM.MaNV = @MaNV

-- Tìm top món ăn bán chạy nhất Chi Nhánh sp_TopMonAnChayNhatChiNhanh
EXEC sp_TopMonAnChayNhatChiNhanh 2, '20220101', '20221231'

-- Cập nhật hạng thẻ từ sp_UpdateMembershipRanks (IDX_THETHANHVIEN_LoaiThe_DiemTichLuy_NgayDatThe)
UPDATE THETHANHVIEN
SET LoaiThe = 'Silver'
WHERE LoaiThe = 'Gold'
AND DiemTichLuy < 100
AND DATEADD(MONTH, -1, '20251201') <= NgayDatThe;
SELECT * FROM THETHANHVIEN

-- Tính doanh thu theo chi nhánh trong sp_GetTotalRevenue (IDX_HOADON_MaCN)
DECLARE @StartDate Date = '20221201';
DECLARE @EndDate Date = '20221231';
DECLARE @MaCN INT = 2;
SELECT SUM(HoaDon.TongHoaDon)
FROM HoaDon
WHERE (NgayLap BETWEEN @StartDate AND @EndDate) 
AND HOADON.MaCN = @MaCN;

-- Tong so thanh vien moi (IDX_THETHANHVIEN_NgayLap)
DECLARE @StartDate Date = '20221201';
DECLARE @EndDate Date = '20221231';
DECLARE @MaCN INT = 2;
SELECT COUNT(MaThe)
FROM thethanhvien
WHERE (NgayLap BETWEEN @StartDate AND @EndDate)
AND (THETHANHVIEN.MaKH NOT IN ( SELECT makh FROM THETHANHVIEN tv1 WHERE tv1.NgayLap BETWEEN '1970-01-01' AND DateAdd(Day, -1, @StartDate)))
AND THETHANHVIEN.MaNV IN (SELECT MANV FROM DOICN WHERE DOICN.MaCN = @MaCN AND THETHANHVIEN.NgayLap 
BETWEEN NgayBatDau AND (CASE WHEN NgayKetThuc IS NULL THEN GETDATE() ELSE NgayKetThuc END))

/*
UPDATE BAN
SET MaHD = 112, TinhTrang = 0
WHERE MaBan = 24
*/
--Lấy bàn từ MaHD và TinhTrang trong sp_Checkout (IDX_BAN_MaHD)
DECLARE @MaHD INT = 112;
SELECT MaBan, MaCN
FROM BAN
WHERE MaHD = @MaHD AND TinhTrang = 0;