use QLY_NHAHANG
GO

-- Tạo Index cho các bảng dữ liệu

-- Bảng KHACHHANG
CREATE NONCLUSTERED INDEX IDX_KHACHHANG_SDT ON KHACHHANG(SDT);
CREATE NONCLUSTERED INDEX IDX_KHACHHANG_Email ON KHACHHANG(Email);

-- Bảng THETHANHVIEN
CREATE NONCLUSTERED INDEX IDX_THETHANHVIEN_NgayLap ON THETHANHVIEN(NgayLap);
CREATE NONCLUSTERED INDEX IDX_THETHANHVIEN_MaKH ON THETHANHVIEN(MaKH);

-- Bảng MONAN
CREATE NONCLUSTERED INDEX IDX_MONAN_TenMon ON MONAN(TenMon);

-- Bảng HOADON
CREATE NONCLUSTERED INDEX IDX_HOADON_MaThe ON HOADON(MaThe);
CREATE NONCLUSTERED INDEX IDX_HOADON_NgayLap ON HOADON(NgayLap);

-- Bảng PHIEUDATMON
CREATE NONCLUSTERED INDEX IDX_PHIEUDATMON_MaKH ON PHIEUDATMON(MaKH);
CREATE NONCLUSTERED INDEX IDX_PHIEUDATMON_MaNV ON PHIEUDATMON(MaNV);
CREATE NONCLUSTERED INDEX IDX_PHIEUDATMON_MaBan ON PHIEUDATMON(MaBan);

-- Bảng CHONMON
CREATE NONCLUSTERED INDEX IDX_CHONMON_MaPhieu_MaMon ON CHONMON(MaPhieu, MaMon);

-- Bảng DATBAN
CREATE NONCLUSTERED INDEX IDX_DATBAN_NgayDat ON DATBAN(NgayDat);