-- Create Database
IF DB_ID('QLY_NHAHANG') IS NOT NULL
BEGIN
    USE master
	--ALTER DATABASE QLY_NHAHANG
	--SET SINGLE_USER
	--WITH ROLLBACK IMMEDIATE;
    DROP DATABASE QLY_NHAHANG
END

CREATE DATABASE QLY_NHAHANG
GO
-- Sử dụng CSDL đã tạo
USE QLY_NHAHANG
GO

CREATE TABLE TAIKHOAN
(
    Username VARCHAR(30) PRIMARY KEY,
    Password VARCHAR(30) NOT NULL,
    IsActive bit NOT NULL
);
GO

CREATE TABLE KHACHHANG
(
    MaKH INT identity(1,1) PRIMARY KEY,
    Username VARCHAR(30),
    HoTen NVARCHAR(50) NOT NULL,
    SDT VARCHAR(12) NOT NULL,
    -- tính luôn trường hợp số nước ngoài
    Email VARCHAR(50),
    CCCD CHAR(12),
    GioiTinh VARCHAR(6),

    CONSTRAINT CK_KHACHHANG_GioiTinh CHECK (GioiTinh = 'Male' or Gioitinh = 'Female'),
    CONSTRAINT CK_KHACHHANG_CCCD CHECK (LEN(CCCD) = 12 AND CCCD NOT LIKE '%[^0-9]%'),
    CONSTRAINT CK_KHACHHANG_SDT CHECK (LEN(SDT) = 10 AND SDT NOT LIKE '%[^0-9]%')
);
GO

CREATE TABLE BOPHAN
(
    MaBP CHAR(2) PRIMARY KEY,
    TenBoPhan NVARCHAR(50) NOT NULL,
    Luong DECIMAL (18, 2) NOT NULL DEFAULT(0)
);
GO

CREATE TABLE NHANVIEN
(
    MaNV INT IDENTITY(1, 1) PRIMARY KEY,
    HoTen NVARCHAR(50) NOT NULL,
    NgaySinh DATE NOT NULL,
    NgayVaoLam DATE NOT NULL,
    NgayNghiViec DATE,
    Username VARCHAR(30),
    MaBP CHAR(2) NOT NULL,
    -- BV, TN, PV, BP, GD, QL, TV
    CN_Hientai CHAR(2) NOT NULL,

    CONSTRAINT CK_NgayVaoLam_NgayNghiViec CHECK (NgayNghiViec IS NULL OR NgayVaoLam <= NgayNghiViec)
);
GO

CREATE TABLE THETHANHVIEN
(
    MaThe CHAR(6) PRIMARY KEY,
    -- sửa từ 8 thành 6
    NgayLap DATE NOT NULL,
    LoaiThe NVARCHAR(50) NOT NULL,
    DiemTichLuy INT DEFAULT 0 NOT NULL,
    IsActive BIT NOT NULL,
    MaKH INT NOT NULL,
    MaNV INT NOT NULL,

    CONSTRAINT CK_THETHANHVIEN_LoaiThe CHECK (LoaiThe = 'Silver' or LoaiThe = 'Gold' or LoaiThe = 'Normal'),
    CONSTRAINT CK_THETHANHVIEN_DIEM CHECK (DiemTichLuy >= 0)
);
GO

CREATE TABLE HOADON
(
    MaHD INT IDENTITY(1, 1),
    GiamGia DECIMAL(18, 2),
    TongHoaDon DECIMAL(18, 2) NOT NULL,
    MaThe CHAR(6),
    NgayLap DATE NOT NULL,
    isEATIN BIT NOT NULL,
    -- ăn tại chỗ hoặc mang về

	CONSTRAINT PK_HOADON PRIMARY KEY (MaHD),
    CONSTRAINT CK_HOADON_GIAMGIA CHECK (GiamGia >= 0 AND GiamGia <= TongHoaDon),
    CONSTRAINT CK_HOADON_TONGTIEN CHECK (TongHoaDon >= 0)
);
GO

CREATE TABLE PHIEUDANHGIA
(
    MaPhieuDG INT IDENTITY(1, 1) PRIMARY KEY,
    DiemPhucVu TINYINT NOT NULL,
    DiemViTri TINYINT,
    DiemMonAn TINYINT,
    DiemKhongGian TINYINT,
    DiemGiaCa TINYINT,
    MaHD INT,

    CONSTRAINT CK_DiemPhucVu CHECK (DiemPhucVu BETWEEN 1 AND 5),
    CONSTRAINT CK_DiemViTri CHECK (DiemViTri BETWEEN 1 AND 5),
    CONSTRAINT CK_DiemMonAn CHECK (DiemMonAn BETWEEN 1 AND 5),
    CONSTRAINT CK_DiemKhongGian CHECK (DiemKhongGian BETWEEN 1 AND 5),
    CONSTRAINT CK_DiemGiaCa CHECK (DiemGiaCa BETWEEN 1 AND 5)
);
GO

CREATE TABLE KHUVUC
(
    MaKV CHAR(2) PRIMARY KEY,
    -- MB, MT, MN
    TenKhuVuc NVARCHAR(20) NOT NULL
);
GO

CREATE TABLE CHINHANH
(
    MaCN CHAR(2) PRIMARY KEY,
    TenCN NVARCHAR(100) NOT NULL,
    DiaChi NVARCHAR(255) NOT NULL,
    ThoiGianMo TIME NOT NULL,
    ThoiGianDong TIME NOT NULL,
    SDT CHAR(10) NOT NULL,
    CoXeMay BIT,
    CoXeHoi BIT,
    MaKV CHAR(2) NOT NULL,
    MaNVQuanLy INT
);
GO

CREATE TABLE DOICN
(
    MaNV INT,
    MaCN CHAR(2),
    NgayBatDau DATE,
    NgayKetThuc DATE,

    PRIMARY KEY (MaNV, MaCN, NgayBatDau),

    CONSTRAINT CK_NgayBatDau_NgayKetThuc CHECK (NgayKetThuc IS NULL OR NgayBatDau <= NgayKetThuc)
);
GO

-- CREATE TABLE THUCDON
-- (
--     MaTD INT PRIMARY KEY IDENTITY(1, 1),
--     MaCN INT,

--     CONSTRAINT FK_THUCDON_CHINHANH
--     FOREIGN KEY (MaCN) REFERENCES CHINHANH(MaCN)
-- ); -->>>>>>
-- GO

CREATE TABLE MONAN
(
    MaMon SMALLINT PRIMARY KEY IDENTITY(1, 1),
    TenMon NVARCHAR(100) NOT NULL,
    PhanLoai NVARCHAR(50) NOT NULL,
    GiaTien DECIMAL(18, 2) NOT NULL,
    GiaoHang BIT NOT NULL
);
GO

CREATE TABLE PHUCVU
(
    MaTD CHAR(2),
    MaMon SMALLINT,
    isServed BIT NOT NULL,
    PRIMARY KEY (MaTD, MaMon)
);
GO

CREATE TABLE PHIEUDATMON
(
    MaPhieu INT IDENTITY(1,1) PRIMARY KEY,
    NgayLap DATE NOT NULL,
    MaBan CHAR(3) NOT NULL,
    TongTien DECIMAL(18, 2),
    MaKH INT,
    MaNV INT NOT NULL,
    MaHD INT
);
GO

CREATE TABLE CHONMON
(
    MaPhieu INT,
    MaMon SMALLINT,
    SoLuong INT NOT NULL,
    TongTien INT NOT NULL,

    PRIMARY KEY (MaPhieu, MaMon),

    CONSTRAINT CK_CHONMON_SOLUONG CHECK (SoLuong > 0),
    CONSTRAINT CK_CHONMON_TONGTIEN CHECK (TongTien >= 0)
);
GO

CREATE TABLE DATBAN
(
    MaDatBan SMALLINT IDENTITY(1, 1) PRIMARY KEY,
    NgayDat DATE NOT NULL,
    GioDat TIME NOT NULL,
    SoLuong INT NOT NULL,
    ChiNhanh CHAR(2) NOT NULL,
    GhiChu NVARCHAR(255),
    MaKH INT,
    MaPhieu INT,

    CONSTRAINT CK_DATBAN_SOLUONG CHECK (SoLuong > 0)
);
GO

CREATE TABLE BAN 
(
    MaBan CHAR(3) PRIMARY KEY,
    MaHD INT,
    TinhTrang BIT 
);
GO

-- Adding Foreign Keys
ALTER TABLE KHACHHANG
ADD CONSTRAINT FK_KHACHHANG_TAIKHOAN
FOREIGN KEY (Username) REFERENCES TAIKHOAN(Username);

ALTER TABLE NHANVIEN
ADD CONSTRAINT FK_NHANVIEN_TAIKHOAN
FOREIGN KEY (Username) REFERENCES TAIKHOAN(Username),
CONSTRAINT FK_NHANVIEN_BOPHAN
FOREIGN KEY (MaBP) REFERENCES BOPHAN(MaBP),
CONSTRAINT FK_NHANVIEN_CHINHANH
FOREIGN KEY (CN_Hientai) REFERENCES CHINHANH(MaCN);

ALTER TABLE THETHANHVIEN
ADD CONSTRAINT FK_THETHANHVIEN_KHACHHANG
FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH),
CONSTRAINT FK_THETHANHVIEN_NHANVIEN
FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV);

ALTER TABLE HOADON
ADD CONSTRAINT FK_HOADON_THETHANHVIEN
FOREIGN KEY (MaThe) REFERENCES THETHANHVIEN(MaThe);

ALTER TABLE PHIEUDANHGIA
ADD CONSTRAINT FK_PHIEUDANHGIA_HOADON
FOREIGN KEY (MaHD) REFERENCES HOADON(MaHD);

ALTER TABLE CHINHANH
ADD CONSTRAINT FK_CHINHANH_KHUVUC
FOREIGN KEY (MaKV) REFERENCES KHUVUC(MaKV),
CONSTRAINT FK_CHINHANH_NHANVIEN
FOREIGN KEY (MaNVQuanLy) REFERENCES NHANVIEN(MaNV);

ALTER TABLE DOICN
ADD CONSTRAINT FK_DOICN_NHANVIEN
FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV),
CONSTRAINT FK_DOICN_CHINHANH
FOREIGN KEY (MaCN) REFERENCES CHINHANH(MaCN);

ALTER TABLE PHUCVU
ADD CONSTRAINT FK_PHUCVU_THUCDON
FOREIGN KEY (MaTD) REFERENCES CHINHANH(MaCN),
CONSTRAINT FK_PHUCVU_MONAN
FOREIGN KEY (MaMon) REFERENCES MONAN(MaMon);

ALTER TABLE PHIEUDATMON
ADD CONSTRAINT FK_PHIEUDATMON_KHACHHANG
FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH),
CONSTRAINT FK_PHIEUDATMON_NHANVIEN
FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV),
CONSTRAINT FK_PHIEUDATMON_HOADON
FOREIGN KEY (MaHD) REFERENCES HOADON(MaHD);

ALTER TABLE CHONMON
ADD CONSTRAINT FK_CHONMON_PHIEUDATMON
FOREIGN KEY (MaPhieu) REFERENCES PHIEUDATMON(MaPhieu),
CONSTRAINT FK_CHONMON_MONAN
FOREIGN KEY (MaMon) REFERENCES MONAN(MaMon);

ALTER TABLE DATBAN
ADD CONSTRAINT FK_DATBAN_KHACHHANG
FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH),
CONSTRAINT FK_DATBAN_PHIEUDATMON
FOREIGN KEY (MaPhieu) REFERENCES PHIEUDATMON(MaPhieu),
CONSTRAINT FK_DATBAN_CHINHANH
FOREIGN KEY (ChiNhanh) REFERENCES CHINHANH(MaCN);
GO

ALTER TABLE PHIEUDATMON 
ADD CONSTRAINT FK_PHIEUDATMON_BAN
FOREIGN KEY (MaBan) REFERENCES BAN(MaBan)

ALTER TABLE BAN
ADD CONSTRAINT FK_BAN_HOADON
FOREIGN KEY (MaHD) REFERENCES HOADON(MaHD)