-- Create Database
IF DB_ID('QLY_NHAHANG') IS NOT NULL
	USE master
	DROP DATABASE QLY_NHAHANG
CREATE DATABASE QLY_NHAHANG
GO
-- Sử dụng CSDL đã tạo
USE QLY_NHAHANG
GO

CREATE TABLE TAIKHOAN (
    Username NVARCHAR(50) PRIMARY KEY,
    Password NVARCHAR(100) NOT NULL,
    IsActive bit NOT NULL
);
GO

CREATE TABLE KHACHHANG (
    MaKH INT identity(1,1) PRIMARY KEY,
	Username NVARCHAR(50) NOT NULL,
    HoTen NVARCHAR(100) NOT NULL,
    SDT VARCHAR(10) NOT NULL,
    Email NVARCHAR(100),
    CCCD VARCHAR(12),
    GioiTinh NVARCHAR(6)

	CONSTRAINT CK_KHACHHANG_GioiTinh CHECK (GioiTinh = 'Male' or Gioitinh = 'Female'),
	CONSTRAINT CK_KHACHHANG_CCCD CHECK (LEN(CCCD) = 12 AND CCCD NOT LIKE '%[^0-9]%'),
	CONSTRAINT CK_KHACHHANG_SDT CHECK (LEN(SDT) = 10 AND SDT NOT LIKE '%[^0-9]%'),

	CONSTRAINT FK_KHACHHANG_TAIKHOAN
	FOREIGN KEY (Username) References TAIKHOAN(Username)
);
GO

CREATE TABLE BOPHAN (
    MaBP INT IDENTITY(1, 1) PRIMARY KEY,
    TenBoPhan NVARCHAR(100) NOT NULL,
    Luong DECIMAL(18, 2) NOT NULL DEFAULT (10000000 + CAST(RAND() * 10000000 AS INT))
);
GO

CREATE TABLE NHANVIEN (
    MaNV INT IDENTITY(1, 1) PRIMARY KEY,
    HoTen NVARCHAR(100) NOT NULL,
    NgaySinh DATE NOT NULL,
    NgayVaoLam DATE NOT NULL,
    NgayNghiViec DATE,
	Username NVARCHAR(50) NOT NULL,
	MaBP INT,

	CONSTRAINT CK_NgayVaoLam_NgayNghiViec
    CHECK (NgayNghiViec IS NULL OR NgayVaoLam <= NgayNghiViec),

	CONSTRAINT FK_NHANVIEN_TAIKHOAN
	FOREIGN KEY (Username) References TAIKHOAN(Username),

	CONSTRAINT FK_NHANVIEN_BOPHAN 
	FOREIGN KEY (MaBP) REFERENCES BOPHAN(MaBP)
);
GO

CREATE TABLE THETHANHVIEN (
    MaThe CHAR(8) PRIMARY KEY, 
    NgayLap DATE NOT NULL,
    LoaiThe NVARCHAR(50) NOT NULL,
    DiemTichLuy INT DEFAULT 0 NOT NULL,
    IsActive BIT NOT NULL,
    MaKH INT NOT NULL,
	MaNV INT NOT NULL,

	CONSTRAINT CK_THETHANHVIEN_LoaiThe
	CHECK (LoaiThe = 'Silver' or LoaiThe = 'Gold' or LoaiThe = 'Normal'),

	CONSTRAINT CK_THETHANHVIEN_DIEM CHECK (DiemTichLuy >= 0),

    CONSTRAINT FK_THETHANHVIEN_KHACHHANG 
	FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH),
	
    CONSTRAINT FK_THETHANHVIEN_NHANVIEN 
	FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV),
);
GO

CREATE TABLE HOADON (
    MaHD INT IDENTITY(1, 1) PRIMARY KEY,
    GiamGia DECIMAL(18, 2),
    TongHoaDon DECIMAL(18, 2) NOT NULL,
    MaThe CHAR(8),

	CONSTRAINT CK_HOADON_GIAMGIA CHECK (GiamGia >= 0 AND GiamGia <= TongHoaDon),
    CONSTRAINT CK_HOADON_TONGTIEN CHECK (TongHoaDon >= 0),

    CONSTRAINT FK_HOADON_THETHANHVIEN 
	FOREIGN KEY (MaThe) REFERENCES THETHANHVIEN (MaThe)
);
GO

CREATE TABLE PHIEUDANHGIA (
    MaPhieuDG INT IDENTITY(1, 1)  PRIMARY KEY,
    DiemPhucVu INT,
    DiemViTri INT,
    DiemMonAn INT,
    DiemKhongGian INT,
    DiemGiaCa INT,
    MaHD INT,

	CONSTRAINT CK_DiemPhucVu CHECK (DiemPhucVu BETWEEN 1 AND 5),
    CONSTRAINT CK_DiemViTri CHECK (DiemViTri BETWEEN 1 AND 5),
    CONSTRAINT CK_DiemMonAn CHECK (DiemMonAn BETWEEN 1 AND 5),
    CONSTRAINT CK_DiemKhongGian CHECK (DiemKhongGian BETWEEN 1 AND 5),
    CONSTRAINT CK_DiemGiaCa CHECK (DiemGiaCa BETWEEN 1 AND 5),

    CONSTRAINT FK_PHIEUDANHGIA_HOADON 
	FOREIGN KEY (MaHD) REFERENCES HOADON(MaHD)
);
GO

CREATE TABLE KHUVUC (
    MaKV INT IDENTITY(1, 1) PRIMARY KEY,
    TenKhuVuc NVARCHAR(100) NOT NULL
);
GO

CREATE TABLE CHINHANH (
    MaCN INT IDENTITY(1, 1) PRIMARY KEY,
    TenCN NVARCHAR(100) NOT NULL,
    DiaChi NVARCHAR(255) NOT NULL,
    ThoiGianMo TIME NOT NULL,
    ThoiGianDong TIME NOT NULL,
    SDT VARCHAR(10) NOT NULL,
    CoXeMay BIT,
    CoXeHoi BIT,
	MaKV INT NOT NULL,
	MaNVQuanLy INT,
	
	CONSTRAINT FK_CHINHANH_KHUVUC
	FOREIGN KEY (MaKV) REFERENCES KHUVUC(MaKV),

	CONSTRAINT FK_CHINHANH_NHANVIEN
	FOREIGN KEY (MaNVQuanLy) REFERENCES NHANVIEN(MaNV)
);
GO

CREATE TABLE DOICN (
    MaNV INT,
    MaCN INT,
    NgayBatDau DATE, --Constraint
    NgayKetThuc DATE,

    PRIMARY KEY (MaNV, MaCN, NgayBatDau),

	CONSTRAINT CK_NgayBatDau_NgayKetThuc
    CHECK (NgayKetThuc IS NULL OR NgayBatDau <= NgayKetThuc),

    CONSTRAINT FK_DOICN_NHANVIEN 
	FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV),

	CONSTRAINT FK_DOICN_CHINHANH
    FOREIGN KEY (MaCN) REFERENCES CHINHANH(MaCN)
);
GO

CREATE TABLE THUCDON (
    MaTD INT PRIMARY KEY IDENTITY(1, 1),
	MaCN INT,

	CONSTRAINT FK_THUCDON_CHINHANH
    FOREIGN KEY (MaCN) REFERENCES CHINHANH(MaCN)
);
GO

CREATE TABLE MONAN (
    MaMon INT PRIMARY KEY IDENTITY(1, 1),
    TenMon NVARCHAR(100) NOT NULL,
    PhanLoai NVARCHAR(50) NOT NULL,
    GiaTien DECIMAL(18, 2) NOT NULL
);
GO

CREATE TABLE PHUCVU (
    MaTD INT,
    MaMon INT,
    isServed BIT NOT NULL,
    PRIMARY KEY (MaTD, MaMon),

	CONSTRAINT FK_PHUCVU_THUCDON
    FOREIGN KEY (MaTD) REFERENCES THUCDON(MaTD),

	CONSTRAINT FK_PHUCVU_MONAN
    FOREIGN KEY (MaMon) REFERENCES MONAN(MaMon)
);
GO

CREATE TABLE PHIEUDATMON (
    MaPhieu INT IDENTITY(1,1) PRIMARY KEY,
    NgayLap DATE NOT NULL,
    MaBan NVARCHAR(50) NOT NULL,
    TongTien DECIMAL(18, 2),
    MaKH INT,
	MaNV INT NOT NULL,
	MaHD INT,

	CONSTRAINT FK_PHIEUDATMON_KHACHHANG
    FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH),

	CONSTRAINT FK_PHIEUDATMON_NHANVIEN
	FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV),

	CONSTRAINT FK_PHIEUDATMON_HOADON
	FOREIGN KEY (MaHD) REFERENCES HOADON(MaHD)
);
GO

CREATE TABLE CHONMON (
    MaPhieu INT,
    MaMon INT,
    SoLuong INT NOT NULL,
    TongTien DECIMAL(18, 2) NOT NULL,

    PRIMARY KEY (MaPhieu, MaMon),

	CONSTRAINT CK_CHONMON_SOLUONG CHECK (SoLuong > 0),
    CONSTRAINT CK_CHONMON_TONGTIEN CHECK (TongTien >= 0),

	CONSTRAINT FK_CHONMON_PHIEUDATMON
    FOREIGN KEY (MaPhieu) REFERENCES PHIEUDATMON(MaPhieu),

	CONSTRAINT FK_CHONMON_MONAN
    FOREIGN KEY (MaMon) REFERENCES MonAn(MaMon)
);
GO

CREATE TABLE DATBAN (
    MaDatBan INT IDENTITY(1, 1) PRIMARY KEY,
    NgayDat DATE NOT NULL,
    GioDat TIME NOT NULL,
    SoLuong INT NOT NULL,
    CuaHang NVARCHAR(100),
    GhiChu NVARCHAR(255),
    MaKH INT,
	MaPhieu INT,

	CONSTRAINT CK_DATBAN_SOLUONG CHECK (SoLuong > 0),

	CONSTRAINT FK_DATBAN_KHACHHANG
    FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH),

	CONSTRAINT FK_DATBAN_PHIEUDATMON
	FOREIGN KEY (MaPhieu) REFERENCES PHIEUDATMON(MaPhieu)
);
GO