services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Khanh076942542"
      TZ: "Asia/Ho_Chi_Minh"
    ports:
      - "1433:1433"
    volumes:
      - advanced_db:/var/opt/mssql/data
volumes:
  advanced_db: